export default function MockBanner() {
  return (
    <div className="flex items-start gap-3 bg-amber-500/10 border border-amber-500/30 rounded-xl px-4 py-3">
      <div className="shrink-0 mt-0.5">
        <svg className="w-5 h-5 text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
            d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
      </div>
      <div>
        <p className="text-sm font-semibold text-amber-300">Mock Analysis Mode</p>
        <p className="text-xs text-amber-400/80 mt-0.5">
          <code className="font-mono">CLAUDE_API_KEY</code> is not configured.
          Findings are generated by rule-based analysis (unattached volumes, idle load balancers,
          unassigned IPs, etc.) using real DigitalOcean pricing — not Claude AI.
          Set the key and re-run to get AI-powered recommendations.
        </p>
      </div>
    </div>
  )
}
